repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0  # Use the latest version
    hooks:
      - id: shellcheck
        args: ["--severity=error", "--exclude=SC1071"]  # Ignore SC1071 error

  - repo: local
    hooks:
      - id: save-vscode-extensions
        name: Save VSCode extensions
        entry: ./vscode/.pre-commit-hook.sh
        language: script
        pass_filenames: false
        files: ^vscode/

  - repo: local
    hooks:
      - id: save-cursor-extensions
        name: Save Cursor extensions
        entry: ./cursor/.pre-commit-hook.sh
        language: script
        pass_filenames: false
        files: ^cursor/
