repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0  # Use the latest version
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]  # Optional: configure shellcheck 

  - repo: local
    hooks:
      - id: save-vscode-extensions
        name: Save VSCode extensions
        entry: ./vscode/save_code_extensions
        language: script
        pass_filenames: false
        files: ^vscode/

  - repo: local
    hooks:
      - id: save-cursor-extensions
        name: Save Cursor extensions
        entry: ./cursor/save_cursor_extensions
        language: script
        pass_filenames: false
        files: ^cursor/
