# Don't print a new line at the start of the prompt
#add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 20

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
python_binary = "python3"

[git_status]
disabled = true

[aws]
#format = '[$symbol ($profile )($duration )(\($region\) )]($style)'
#symbol = '󰸏'
#disabled=true

[gcloud]
disabled = true

[time]
#disabled=false

[directory]
truncate_to_repo = false
truncation_length = 6
truncation_symbol = "…/"
